DROP TABLE IF EXISTS DOMICILIOS;
CREATE TABLE DOMICILIOS (ID INT AUTO_INCREMENT PRIMARY KEY,
CALLE VARCHAR(200),
NUMERO INT,
LOCALIDAD VARCHAR(100),
PROVINCIA VARCHAR(100));
DROP TABLE IF EXISTS PACIENTES;
CREATE TABLE PACIENTES (ID INT AUTO_INCREMENT PRIMARY KEY,
NOMBRE VARCHAR(100),
DNI INT,
FECHA DATE,
DOMICILIO_ID INT);
INSERT INTO DOMICILIOS (CALLE, NUMERO, LOCALIDAD,PROVINCIA) VALUES
('Calle A',101,'Salta','Salta');
INSERT INTO DOMICILIOS (CALLE, NUMERO, LOCALIDAD,PROVINCIA) VALUES
('Calle B',84,'Salta','Salta');
INSERT INTO PACIENTES (NOMBRE, DNI, FECHA, DOMICILIO_ID) VALUES
('Rodolfo',251,'2022-06-01',1);
INSERT INTO PACIENTES (NOMBRE, DNI, FECHA, DOMICILIO_ID) VALUES
('Ezequiel',858,'2022-06-01',2);
